### PR TITLE
fix: use video icon for video figCaption

### LINKED ISSUE #6145: Incorrect caption icon for video media atoms
The caption icon for videos currently the camera icon, but it should be the video icon.

### PR DESCRIPTION
**Pull request by georgeblahblah**
## What does this change?

- uses a video icon for figure captions beneath videos

## Why?

- to fix #6145 

### Video

| Before      | After      |
|-------------|------------|
| ![before][] | ![after][] |

[before]: https://user-images.githubusercontent.com/705427/194350072-38f6dd6c-85f5-417e-9828-e428c671e1c9.png
[after]: https://user-images.githubusercontent.com/705427/194350067-b5c1808a-46c6-4979-9016-85b5dda70170.png

### Image

| Before      | After      |
|-------------|------------|
| ![before1][] | ![after1][] |

[before1]: https://user-images.githubusercontent.com/705427/194350637-a194371c-5c33-46db-a1f8-d8ef3385a1fb.png
[after1]: https://user-images.githubusercontent.com/705427/194350643-17f59488-8652-4ff9-aa88-a4e77834e378.png

### CODE REVIEW

File: common-rendering/src/components/figCaption.tsx [hunk 1]
```diff
@@ -16,12 +16,18 @@ import { fill, text } from '@guardian/common-rendering/src/editorialPalette';
 
 // ----- Sub-Components ----- //
 
-interface CameraProps {
+enum Variant {
```
Comment (JamieB-gu) [inline common-rendering/src/components/figCaption.tsx:19]: Is `Variant` perhaps quite a generic term? Could we make this more specific by calling it something like `Icon` or `IconVariant`?

File: apps-rendering/src/renderer.ts [hunk 2]
```diff
@@ -10,7 +10,10 @@ import {
 	QandaAtom,
 	TimelineAtom,
 } from '@guardian/atoms-rendering';
-import FigCaption from '@guardian/common-rendering/src/components/figCaption';
+import {
+	default as FigCaption,
+	Variant as FigCaptionVariant,
+} from '@guardian/common-rendering/src/components/figCaption';
```
Comment (JamieB-gu) [inline apps-rendering/src/renderer.ts:16]: FYI, I think this can also be expressed as:

```ts
import FigCaption, {
	Variant as FigCaptionVariant,
} from '@guardian/common-rendering/src/components/figCaption';
```

**Review by JamieB-gu — APPROVED** [review]
Nice! One suggestion.
