### PR TITLE
Fix Reply & Comment parsing

### LINKED ISSUE #10597: Comment Threading Bug
Raised by Stephanie Munro 

"Commenters are flagging an issue with replies not being shown as such when displaying comments as unthreaded. I can replicate it, when using the unthreaded view all comments display as individual comments and you can't see if any are replies to other comments."

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Better parsing on `Comment` and `Reply`

## Why?

Fixes #10597 

Follow-up on #10563 

## Screenshots

| Before      | After      |
| ----------- | ---------- |
| ![before][] | ![after][] |

[before]: https://github.com/guardian/dotcom-rendering/assets/76776/0350cdcb-99f9-45d4-b099-fde2ce3ba617
[after]: https://github.com/guardian/dotcom-rendering/assets/76776/f5e68d0f-fa4a-4ba8-b0e3-28fb61b08321

Running the test on `main` correctly identifies the issue:

image

### CODE REVIEW

**Review by abeddow91 — APPROVED** [review]
❤️ parsing ❤️

File: dotcom-rendering/src/lib/discussion.ts [hunk 1]
```diff
@@ -300,7 +303,7 @@ const discussionApiSuccessSchema = object({
 		isClosedForRecommendation: boolean(),
 		isThreaded: boolean(),
 		title: string(),
-		comments: array(union([commentSchema, replySchema])),
+		comments: array(union([replySchema, commentSchema])),
```
Comment (mxdvl) [inline dotcom-rendering/src/lib/discussion.ts:306]: Not sure why I flipped these… it should not be necessary, but in any case there’s a test now, so it should not matter too much!
