### PR TITLE
fix: add darkmode styling for ClickToView

### LINKED ISSUE #6130: Missing Dark Mode Styles On ClickToView
click-to-view-dark

### PR DESCRIPTION
**Pull request by georgeblahblah**
## What does this change?

- Adds dark mode styling for `ClickToView`
- Validated passes AA colour contrast using the Axe browser extension

## Why?

- fixes #6130

## Screenshots

| Before      | After      |
|-------------|------------|
| ![before][] | ![after][] |

[after]: https://user-images.githubusercontent.com/705427/194335581-700d4421-dae3-424c-b9ad-ca349ae6bed0.png

[before]: https://user-images.githubusercontent.com/705427/194330502-e28f49ae-43a4-43d6-ad86-6aee31c444e5.png

### CODE REVIEW

**Review by JamieB-gu — APPROVED** [review]
Nice!

I'm curious how you made the button change colours as seen in the screenshot? I can't see anything in the code related to the button 🤔 - what am I missing?

**Comment by georgeblahblah** [comment]
> Nice!
> 
> I'm curious how you made the button change colours as seen in the screenshot? I can't see anything in the code related to the button 🤔 - what am I missing?

@JamieB-gu I have an unpushed commit! I'll dismiss your review, sorry!

File: apps-rendering/src/components/ClickToView/index.tsx [hunk 1]
```diff
@@ -94,6 +96,17 @@ const roleButtonText = (role: ArticleElementRole): string => {
...
+const buttonStyles = css`
+	${darkModeCss`
+		color: ${neutral[10]};
+		background-color: ${neutral[86]};
+
+		&:hover {
+			background-color: ${neutral[97]};
+		}
+	`}
+`;
```
Comment (JamieB-gu) [inline apps-rendering/src/components/ClickToView/index.tsx:108]:
```suggestion
const buttonStyles = darkModeCss`
	color: ${neutral[10]};
	background-color: ${neutral[86]};

	&:hover {
		background-color: ${neutral[97]};
	}
`;
```

**Review by JamieB-gu — APPROVED** [review]
