### PR TITLE
Fix contrasts for branding on liveblogs mobile

### LINKED ISSUE #5486: Pull in white sponsor logo on liveblogs
On sponsored liveblogs the sponsor logo sit's on a dark background at mobile breakpoints (until: desktop). Tag manager allows 2 logos to be uploaded. Can we use the white (high contrast) one instead?
Can we also change "Supported by" and "About this content" to be white on smaller breakpoints too

Image 
Image

Tag manager:
Image

### PR DESCRIPTION
**Pull request by bryophyta**
## What does this change?
The background colour for the meta on liveblogs is dark on mobile, light
on desktop.

This commit uses light colours and the light variant of the logo on
smaller breakpoints. (Largely following the pattern already used in
`Contributor.tsx`.)

## Why?
Closes #5486 

## Screenshots

https://www.theguardian.com/football/live/2022/jul/26/england-v-sweden-womens-euro-2022-semi-final-live?dcr&live=true

| Before      | After      |
|-------------|------------|
| image | image |

[before]: https://example.com/before.png
[after]: https://example.com/after.png

### CODE REVIEW

File: dotcom-rendering/src/web/components/Branding.importable.tsx [hunk 1]
```diff
@@ -1,46 +1,132 @@
...
 	padding-bottom: 10px;
 `;
 
-const brandingLabelStyle = css`
-	${textSans.xxsmall()};
-	color: ${neutral[20]};
-`;
+// for liveblog smaller breakpoints article meta is located in the same
+// container as standfirst and needs the same styling as standfirst
+function brandingLabelStyle(palette: Palette, format: ArticleFormat) {
```
Comment (bryophyta) [inline dotcom-rendering/src/web/components/Branding.importable.tsx:12]: I've largely copied this from the existing implementation in `Contributor.tsx` https://github.com/guardian/dotcom-rendering/blob/8f393a42b9a01655dd95d7a492d51c191389cabe/dotcom-rendering/src/web/components/Contributor.tsx#L58-L85

I thought it best not to innovate too much, even though the use-case is a little different, but happy to refactor a bit if needed.

File: dotcom-rendering/src/web/components/Branding.importable.tsx [hunk 2]
```diff
@@ -1,46 +1,132 @@
...
+					a {
+						color: ${palette.text.branding};
+					}
+				`,
+			];
+		}
+	}
+};
+
+const hiddenUntilDesktop = css`
```
Comment (bryophyta) [inline dotcom-rendering/src/web/components/Branding.importable.tsx:103]: I thought this was the simplest way to toggle different img sources according to breakpoints, but is this a DCR-approved pattern? Could toggle background-url instead, or potentially picture srcsets? (though neither feel super semantic for this effect..?)

File: dotcom-rendering/src/web/components/Branding.importable.tsx [hunk 3]
```diff
@@ -1,46 +1,132 @@
...
 
 const brandingLogoStyle = css`
 	padding: 10px 0;
 
 	display: block;
-	img {
+`;
+
+// for liveblog smaller breakpoints article meta is located in the same
+// container as standfirst and needs the same styling as standfirst
```
Comment (mxdvl) [inline dotcom-rendering/src/web/components/Branding.importable.tsx:60]: JSDoc please?

File: dotcom-rendering/src/web/components/Branding.importable.tsx (hunk 2 above)
Comment (mxdvl) [reply dotcom-rendering/src/web/components/Branding.importable.tsx:103]: There's a `Hide` component, I believe?

**Review by mxdvl — APPROVED** [review]
👌

**Review by ioannakok — APPROVED** [review]
Looks good to me!
