### PR TITLE
Add Fronts container: fixed/small/slow-III

### LINKED ISSUE #5132: "fixed/small/slow-III" (`323`)

### PR DESCRIPTION
**Pull request by bryophyta**
## What does this change?

Adds a container for the `fixed/small/slow-III` Fronts layout.

## Why?

Part of the Fronts migration (see: #4720, closes #5132)  

## Screenshots

| Before (Frontend prod)    | After (DCR local)     |
|-------------|------------|
| Before on Frontend | After on DCR |
| Before, Frontend, tablet | After, DCR, tablet |
| Before, Frontend, mobile | After, DCR, mobile |

Two of the visible differences ('Show More' button and 'Hide' link) are distinct features which will be added separately for all containers, so not part of this PR.

[before]: https://example.com/before.png
[after]: https://example.com/after.png

### CODE REVIEW

File: dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const TrailTextWrapper = ({
 				padding-right: 5px;
 				padding-bottom: 6px;
 
-				${until.tablet} {
+				${until.desktop} {
```
Comment (bryophyta) [inline dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx:31]: I've added this here because it recreates the behaviour of this container on Frontend. However, it's the sort of change that will have implications for all other cards, too. If there are other requirements for other containers, we'll need to introduce different ways of setting this value for different containers. Any thoughts?

File: dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+	return (
+		<UL direction="row">
+			{smallTrails.map((trail, index) => {
+				return (
+					<LI
+						padSides={true}
+						showDivider={index > 0}
+						padBottomOnMobile={true}
+						percentage={index === 0 ? '50%' : '25%'}
```
Comment (bryophyta) [inline dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx:27]: having these properties decided inline is a bit awkward, but the obvious alternative (having two distinct component calls which hard-code all of their relevant values) is a bit awkward too, as it makes it difficult to see what the cards in this container have in common. Given that the decision-rule here is always based on the same criterion ("is it the first card or not?") having the logic inline doesn't seem to bad to me here, but interested to hear people's thoughts!

Comment (bryophyta) [reply dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx:27]: Thanks Ash! I like your suggestion, do we know roughly how many options there would need to be? My only concern is that the system would need to be designed well to avoid recreating the existing complexity, adding multiple override props, etc. Personally I don't know whether/how that would be possible at the moment as I've not looked into the existing combinations of props in enough detail. But were you saying that Frontend already has an abstraction for this? I'd be interested to check that out if you know where to look?

File: dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx (hunk 1 above)
Comment (mxdvl) [reply dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx:31]: I’m a little bit puzzled by this change. This has been introduced in 2019 in [PR #1019](https://github.com/guardian/dotcom-rendering/pull/1019/commits/d5566e2953ba4dbcee290b1b168a3178b84c054f) and I would like to push this to a separate PR if at all possible?

**Review by mxdvl — APPROVED** [review]
This is looking good, but I’d prefer the change from `tablet` to `desktop` to be extracted in its own PR.

File: dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+	showAge,
+}: Props) => {
+	const smallTrails = trails.slice(0, 3);
+
+	return (
+		<UL direction="row">
+			{smallTrails.map((trail, index) => {
+				return (
+					<LI
+						padSides={true}
```
Comment (OllysCoding) [inline dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx:24]: `key={trail.url}` - We must suppress all the warnings!

File: dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx (hunk 1 above)
Comment (oliverlloyd) [reply dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx:31]: +1 for a separate PR for this. This could have impacts in a wider area than just fronts.

**Review by oliverlloyd — APPROVED** [review]
Chip, chip

File: dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx (hunk 2 above)
Comment (AshCorr) [reply dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx:27]: Thats right :) Not saying that you should be doing that in this PR, it would be quite a big task to do this.

Comment (bryophyta) [reply dotcom-rendering/src/web/components/FixedSmallSlowIII.tsx:27]: Okay yep that sounds good, thanks!

File: dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx (hunk 1 above)
Comment (bryophyta) [reply dotcom-rendering/src/web/components/Card/components/TrailTextWrapper.tsx]: Thanks, I've taken it out of this branch now. Do you think it makes sense to add an issue treating  the current behaviour of the trail text as a bug because it diverges from Frontend fronts? Or should we treat this as the baseline now given that it seems to follow an established convention on DCR?
