### PR TITLE
Fix "Supported By" container badge

### LINKED ISSUE #8089: "Supported By" not showing up correctly on
When all cards in a container have branding Frontend adds a "Supported by" badge to the container, this does not seem to happen correctly in DCR.

DCR also renders all containers with the "Branding" tag as labs containers, which I'm not sure is entirely correct.

## DCR

image

## Frontend

image

### PR DESCRIPTION
**Pull request by ioannakok**
Fixes #8089 

## Background

Inspired by [this document](https://docs.google.com/document/d/1yPCmjz33SahtVrzT-7E8Iau6hoo46YFUgLDBJJSJwJw/edit) which explains the different types of badges we can see on the website, I have created this diagram only for the fronts badges. This PR is fixing an issue with sponsored badges which label [editorially independent content](https://www.theguardian.com/info/2016/jan/25/content-funding) but thought it's worth having a diagram as we might want to [refactor the badges](https://github.com/guardian/dotcom-rendering/milestone/153) code in the future. 

```mermaid
flowchart TD
    A(Fronts badges) --> |e.g. This is Europe. Front or container specific.| A1
    A(Fronts badges)--> |Badges coming from Edition Branding. Front or container specific.| A2
    A1(Content / Design Badges)
    A2(Commercial badges)

    A2-->B1
    A2-->B2
    B1(Fronts branding)
    B2(Container branding)

    B1 --> C1
    B2-->C1
    B2-->C2
    C1(Branding)
    C2(MultiPaidBranding)

    C1 --> D1
    C1 --> D2
    C1 --> D3
    D1(Paid Content)
    D2(Sponsored)
    D3(Foundation)

```

## What does this change?
* Renames `editionBranding` to `frontEditionBranding` in `FrontSection` props to be able to separate it from specific to the container branding. For now we're only passing container sponsor branding in order to fix the ticket bug but we could refactor in the future to cover the rest of `Branding` types.
* Introduces `collectionBranding` of type `Branding` in `DCRCollectionType`. This is a first step to [separate the badge from branding logic](https://github.com/guardian/dotcom-rendering/issues/8435) 
* Adds one more condition to show a Labs container: all cards should be of type "paid content" 

## Why?
We need to be able to label our [content with funding from outside parties](https://www.theguardian.com/info/2016/jan/25/content-funding) correctly  

## Future work
* This PR tries to make it easier to pick up [the badges related work](https://github.com/guardian/dotcom-rendering/milestone/153) that's left. 
* This PR also unblocks https://github.com/guardian/dotcom-rendering/issues/7989 but does not fix it yet. There are some tweaks left to do as part of that ticket.

## Screenshots

| Before      | After      |
| ----------- | ---------- |
| image | image |
| image | image |

### CODE REVIEW

File: dotcom-rendering/src/components/FrontSection.tsx [hunk 1]
```diff
@@ -597,19 +599,9 @@ export const FrontSection = ({
...
-										href={badge.href}
-									/>
-								)}
-							</Hide>
-						)}
-						<div css={titleStyle}>
-							{!isOnPaidContentFront && (
-								<Hide from="leftCol">
+						{!isOnPaidContentFront &&
+							containerSponsorBranding === undefined && (
```
Comment (ioannakok) [inline dotcom-rendering/src/components/FrontSection.tsx:603]: Is there a better, more TypeScript to do this?

File: dotcom-rendering/src/components/FrontSection.tsx [hunk 2]
```diff
@@ -628,29 +632,29 @@ export const FrontSection = ({
 								editionId={editionId}
 							/>
 							{!isOnPaidContentFront &&
-								!!editionBranding &&
-								editionBranding.branding &&
+								!!frontEditionBranding &&
+								frontEditionBranding.branding &&
```
Comment (arelra) [inline dotcom-rendering/src/components/FrontSection.tsx:636]: Is it possible to extract these long conditionals to named consts that give some insight into what the resulting boolean is? This might not be entirely accurate but something like `firstFrontEditionBranding`?. Appreciate this might be difficult so will leave it with you if you think it is possible to convey the meaning succinctly :)

Comment (ioannakok) [reply dotcom-rendering/src/components/FrontSection.tsx:636]: Yes! Will do, thanks for the suggestion!
