### PR TITLE
Fix twitter handle colour in liveblogs below desktop

### LINKED ISSUE #4482: twitter handle needs colour logic
In this scenario (mobile) is should be white, then grey at wider breakpoints when we introduce the leftColumn

image

### PR DESCRIPTION
**Pull request by ioannakok**
Closes #4482 

## What does this change?
Adds colour logic for twitter handle. This fixes the colour in liveblogs for breakpoints below desktop (980px).

## Why?
To match the liveblog designs.

## Screenshots

| Before      | After      |
|-------------|------------|
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |

[before]: https://example.com/before.png
[after]: https://example.com/after.png

### CODE REVIEW

**Review by HarryFischer — APPROVED** [review]
👍

File: dotcom-rendering/src/web/lib/decidePalette.ts [hunk 1]
```diff
@@ -1055,6 +1059,7 @@ export const decidePalette = (format: ArticleFormat): Palette => {
 			matchTitle: textMatchTitle(),
 			byline: textByline(format),
 			twitterHandle: textTwitterHandle(format),
+			twitterHandleLiveBackground: textTwitterHandleLiveBackground(),
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/lib/decidePalette.ts:1062]: Can we 
1) drop 'background' from the name here? It's already implied by the structure of the object
2) drop 'live' as this is implied by the usage of `format`

Comment (oliverlloyd) [reply dotcom-rendering/src/web/lib/decidePalette.ts:1062]: For this to work you will need to pass in `format`

File: dotcom-rendering/src/web/components/Contributor.tsx [hunk 2]
```diff
@@ -15,25 +16,59 @@ import TwitterIcon from '../../static/icons/twitter.svg';
...
+		fill: ${neutral[46]};
+	}
+
+	a {
+		color: ${palette.text.twitterHandle};
+	}
+`;
+
+const twitterHandleColour = (palette: Palette, format: ArticleFormat) => {
+	switch (format.design) {
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/components/Contributor.tsx:32]: I think - if I'm reading this right - this switch needs to happen in `decidePalette`?

File: dotcom-rendering/src/web/components/Contributor.tsx [hunk 3]
```diff
@@ -15,25 +16,59 @@ import TwitterIcon from '../../static/icons/twitter.svg';
 import { interactiveLegacyClasses } from '../layouts/lib/interactiveLegacyStyling';
 import { decidePalette } from '../lib/decidePalette';
 
-const twitterHandleStyles = (palette: Palette) => css`
-	${textSans.xxsmall()};
-	font-weight: bold;
+const defaultTwitterHandleColour = (palette: Palette) => css`
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/components/Contributor.tsx:19]: This is subject so take it or leave it but I find nesting css variables can be confusing. I am a fan of keeping things simple and having all the css code used by a variable declaration contained inside itself. And then you put any logic in `<div css={myLogic && simpleCss}>`

File: dotcom-rendering/src/web/lib/decidePalette.ts (hunk 1 above)
Comment (oliverlloyd) [reply dotcom-rendering/src/web/lib/decidePalette.ts:1062]: Ahh, I think I see what you are trying to do here. You want to vary the colour based something not contained in `format` like context or a breakpoint?

Comment (ioannakok) [reply dotcom-rendering/src/web/lib/decidePalette.ts:1062]: Exactly! I want to vary the colour based on the breakpoint. Do you think `twitterHandleBelowDesktop` would make more sense? And maybe something like:

```suggestion
                         // Call it like that and pass format
			twitterHandleBelowDesktop: textTwitterHandleBelowDesktop(format),
			
			// And in palette 
			const textTwitterHandleBelowDesktop = (format: ArticleFormat): string => {
			        if(format.design === ArticleFormat.Liveblog)
			               return WHITE;
			         
			         return textTwitterHandle(format);      	
                         };
```

What do you think?

Comment (ioannakok) [reply dotcom-rendering/src/web/lib/decidePalette.ts]: I pushed a 2nd version of the code. Let me know what you think and if it makes sense!

File: dotcom-rendering/src/web/components/Contributor.tsx [hunk 4]
```diff
@@ -15,25 +16,46 @@ import TwitterIcon from '../../static/icons/twitter.svg';
 import { interactiveLegacyClasses } from '../layouts/lib/interactiveLegacyStyling';
 import { decidePalette } from '../lib/decidePalette';
 
-const twitterHandleStyles = (palette: Palette) => css`
+const twitterHandleColour = (palette: Palette) => css`
+	color: ${palette.text.twitterHandleBelowDesktop};
+
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/components/Contributor.tsx:21]: Just an observation (and this is _very_ subjective), maybe the different groups of css properties can be grouped together without spaces in-between? Personally I would find it easier to distinguish them like that but hey, we all feel space differently!

File: dotcom-rendering/src/web/components/Contributor.tsx [hunk 5]
```diff
@@ -15,25 +16,46 @@ import TwitterIcon from '../../static/icons/twitter.svg';
...
+		svg {
+			fill: ${neutral[46]};
+		}
+
+		a {
+			color: ${palette.text.twitterHandle};
+		}
+	}
+`;
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/components/Contributor.tsx:41]: 🎯 this makes total sense!

File: dotcom-rendering/src/web/lib/decidePalette.ts [hunk 6]
```diff
@@ -157,6 +157,12 @@ const textTwitterHandle = (format: ArticleFormat): string => {
 	return text.supporting;
 };
 
+const textTwitterHandleBelowDesktop = (format: ArticleFormat): string => {
+	if (format.design === ArticleDesign.LiveBlog) return WHITE;
+
+	return textTwitterHandle(format);
+};
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/lib/decidePalette.ts:164]: 💯 This is spot on

File: dotcom-rendering/src/web/lib/decidePalette.ts [hunk 7]
```diff
@@ -1126,6 +1138,7 @@ export const decidePalette = (format: ArticleFormat): Palette => {
 			richLink: fillRichLink(format),
 			quoteIcon: fillQuoteIcon(format),
 			blockquoteIcon: fillBlockquoteIcon(format),
+			twitterHandleBelowDesktop: fillTwitterHandleBelowDesktop(format),
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/lib/decidePalette.ts:1141]: There's no `fill.twitterHandle` here, is that because the designs don't need it?

**Review by oliverlloyd — APPROVED** [review]
This is spot on! 

This is defo a tricky area, `decidePalette` handles most use cases well but occasionally the design requirements are more complex but this feels like a great way to handle that.

Thanks for making the extra effort on this 🙏
