### PR TITLE
Fix share icons links

### LINKED ISSUE #4193: Social share buttons missing block id
Each liveblog post has Facebook and Twitter share buttons at the bottom. 

In Frontend these contain the block id, so the user is directed to that specific block on a click from the social platform.
e.g. 
https://www.theguardian.com/world/live/2022/mar/06/russia-ukraine-war-biden-and-zelenskiy-discuss-more-support-for-ukraine-as-visa-mastercard-pull-out-of-russia-live?CMP=share_btn_tw&page=with:block-6224359f8f084225869781f8#block-6224359f8f084225869781f8 

In DCR the block id is missing from the URL.
e.g. 
https://www.theguardian.com/world/live/2022/mar/06/russia-ukraine-war-biden-and-zelenskiy-discuss-more-support-for-ukraine-as-visa-mastercard-pull-out-of-russia-live 

Not sure what the CMP parameter is used for but that is also missing for both Facebook and Twitter.

### LINKED ISSUE #4534: Missing block ID in share links
_Reported by:_ Dave Earley (Central Production)
_Via:_ Email–Live blog social share buttons
_On:_ April 6 2022

> I've just noticed the social share buttons on individual blocks in the live blog no longer carry the individual block permalink. Has a change been made recently to remove those from share buttons?
> 
> So when hitting the Twitter or Facebook button in a live blog block
> Screen Shot 2022-04-07 at 11.10.37 am.png
> 
> instead of auto-completing the tweet with the block's permalink URL like it should
> https://www.theguardian.com/australia-news/live/2022/apr/07/australia-news-live-updates-weather-nsw-victoria-floods-coronavirus-covid-omicron-scott-morrison-anthony-albanese?page=with:block-624e258c8f0887d7b40d5571#block-624e258c8f0887d7b40d5571
> 
> Now it only adds the top-level blog URL, which isn't great for discovery if people are trying to share a specific block. 
> https://www.theguardian.com/australia-news/live/2022/apr/07/australia-news-live-updates-weather-nsw-victoria-floods-coronavirus-covid-omicron-scott-morrison-anthony-albanese 
> What it should also automatically add to the permalink block link there when using the Twitter share button is the specific Twitter share button campaign code ?CMP=share_btn_tw 
Which should show in that clickthrough to the Twitter compose field as:

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Refactors the way `ShareIcons` links work to use `URL` and `URLSearchParams`. Add the campaign/`CMP` and block ID for liveblogs.

Using these constructors is more verbose and makes it explicit what we're trying to achieve with these complex, nested URLs. I don't think we need to worry about browser support, as these are only used server-side: [node supports it since v6/7](https://nodejs.org/docs/latest-v14.x/api/url.html#url_class_urlsearchparams).

Also: fix small spelling mistakes.

## Why?

Previously, we did not include block IDs in share links. This meant sharing on Twitter would always link to the first page of a blog.

Fixes #4193 
Fixes #4534 

This also places the campaign code as part of the Guardian URL, so we can measure referrals more accurately. Previously, the campaign code was passed to the platform shared on, which they probably disregarded.

### Before

image

### After

image

### CODE REVIEW

File: dotcom-rendering/src/web/components/ShareIcons.tsx [hunk 1]
```diff
@@ -218,9 +256,14 @@ export const ShareIcons = ({
...
 				<li css={liStyles(size)} key="linkedIn">
 					<a
-						href={`http://www.linkedin.com/shareArticle?title=${encodeTitle(
-							webTitle,
-						)}&mini=true&url=${encodeUrl(pageId)}`}
+						href={`http://www.linkedin.com/shareArticle?=${new URLSearchParams(
+							{
+								title: encodeTitle(webTitle),
+								mini: 'true',
+								// TODO?: add &CMP=share_btn_*
```
Comment (mxdvl) [inline dotcom-rendering/src/web/components/ShareIcons.tsx:263]: Is there a CMP code for LinkedIn?

File: dotcom-rendering/src/web/components/ShareIcons.tsx [hunk 2]
```diff
@@ -123,15 +125,32 @@ const iconStyles = ({
...
+	pageId: string;
+	CMP?: string;
+	blockId?: string;
+}) => {
+	const searchParams = new URLSearchParams({});
+	if (CMP) searchParams.append('CMP', CMP);
+	if (blockId) searchParams.append('page', `with:block-${blockId}`);
 
-const encodeTitle = (webTitle: string): string => {
-	return encodeURIComponent(webTitle.replace(/Leave.EU/gi, 'Leave. EU'));
```
Comment (oliverlloyd) [inline dotcom-rendering/src/web/components/ShareIcons.tsx:131]: Does `URL` automatically encode?

Comment (mxdvl) [reply dotcom-rendering/src/web/components/ShareIcons.tsx:131]: `URLSearchParams` does, yes: [see for yourself](https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgQwE4ILYRgXhmApgdxgFUAlAGQGVdlgALABWTQgAoBvAWACgZeYoAllAA2uAFwwARAEEYASTBRcSXNAFgA5jApQk6jRIAHMYQhgAzFGADnCARFwBCGAHJ8tAJ44QUAPwuYAB4AIyQYAHoAPkluAF8ASm5uUEgQUQA6YRANFkQUdHSoEB09TRZ4xK5w8JgAbTIAeQBxAF0JSUERXExpAGoFJRU1TV6S-QBSAGY+8YBhSfHpAAZe017LBDA5hekAdjsHcYAmAEZe4933D16wHymAMQvzydnQ86PHyYBRSRhuIA).

Comment (mxdvl) [reply dotcom-rendering/src/web/components/ShareIcons.tsx:131]: I’ve done some testing and it works well on Twitter and Mail, but there is a small risk that `+` for spaces instead of `%20` makes the social platforms unhappy.

**Review by oliverlloyd — APPROVED** [review]
