### PR TITLE
Fronts: Introduce card wrappers & `supportingContentAligment`

### LINKED ISSUE #5918: Sublinks stack in the wrong direction (sometimes)
In some dynamic/fast and dynamic/slow configurations, sublinks stack vertically where they should horizontally

DCR:
image

Frontend:
image

To recreate:
https://m.code.dev-theguardian.com/olly (If no longer on this link, you need a `dynamic/slow` container with 1 very big, 1 big (with 2 sublinks), 4 standards)

### PR DESCRIPTION
**Pull request by OllysCoding**
## What does this change?

Adds a number of cardWrappers to clearly define the layout of FrontCards, depending on factors such as their size, attached image and sublinks, and implements this by refactoring the dynamic containers (further work will be required to also implement this solution to the fixed containers).

### Card Wrappers

This PR introduces a new lib, `cardWrappers.tsx` which contains a series of pre-made card definition which vary by size, image size & position, sublink configuration and other options.

These 'card wrappers' can be used in containers to assist putting together slices & layouts, removing the burden of reading & understanding the increasingly large and complex number of props required for a `FrontCard`.

**Naming Scheme**

Card wrappers are generally named with the `Card<Width%>Media<Width%><OtherOpts>` scheme. 

For example, a card which is designed to span 75% of the container, with media that spans only 50% of the container, would be named:

`Card75Media50`

Such a card might look like:
image

In this case, we also want a similar card wrapper but with the media on the left instead of on the right. To achieve this we can simply create two wrappers, one named `Card75Media50Left` and another `Card75Media50Right`. 

We do this in other cases where features between similarly sized cards may vary, such as a `Tall` variant when it features more text content link trail text & sublinks, or a `Mobile` variant where the image is shown on mobile as well as desktop.

**Usage**

Using a card wrapper is generally as simple as importing it and passing the 3 mandatory props:

```jsx

import { Card75Media50 } from '../libs/cardWrappers.tsx'

...

<LI percentage={"75%"}
     <Card75Media50
          trail={trail}
          showAge={showAge}
          containerPalette={containerPalette}
     />
</LI>
```

### `supportingContentAlignment`

In order to support sublinks displaying correctly, we needed FrontCard to take a prop which indicated whether to align the sublinks horizontally or vertically.

We added this prop `supportingContentAlignment`, which when combined with passing the `supportingContent` array to the card, enabled the configuration of any required sublink layout.

To achieve this, cardWrappers must self-limit the number of sublinks passed to the FrontCard, for example
```jsx
<FrontCard
     supportContent={trail?.supportingContent.slice(0,3)}
/>
```

This is important as different card sizes & layouts will support different maximum number of sublinks, this generally ranges between 2 & 4 for cards which do display sublinks.

Additionally, some cards may vary their alignment depending on the number of sublinks, e.g 
```jsx
<FrontCard
     supportContent={trail?.supportingContent.slice(0,3)}
     supportContentAlignment={trail.supportingContent && trail.supportingContent.length > 2 ? "horizontal" : "vertical"}
/>
```

This complexity is what eventually led us to introducing the 'card wrappers' abstraction detailed above, as more knowledge was being required to implement a FrontCard.

All of the cardWrappers defined in this PR have been configured to correctly support & layout their sublinks based on Frontend's behaviour. 

## Why?

Resolves #5918 (and follow-on issues/discussions #6435, #6495), also closes https://github.com/guardian/dotcom-rendering/issues/6635 and get us closer to parity with frontend and the 1% test.

## Screenshots

| Frontend      | DCR Before    | DCR After |
|-------------|------------|------------|
| ![before][] | ![DCRbefore][] | ![DCRafter][] | 

[before]: https://user-images.githubusercontent.com/102960844/205709490-cb597edf-31d5-4081-91b5-710f95473561.png
[DCRbefore]: https://user-images.githubusercontent.com/102960844/205710658-3eeb4ff4-19ed-452c-b414-af6acd9fc3a0.png
[DCRafter]: https://user-images.githubusercontent.com/102960844/205710472-64e504bf-bdce-4ae0-aadc-4a3a0fccb29a.png

## Whats next

This PR only introduces cardWrappers & implements `supportingContentAlignment` for dynamic containers, issues & PRs will follow for the remaining fixed containers

### CODE REVIEW

File: dotcom-rendering/tsconfig.tsbuildinfo [hunk 1]
```diff
@@ -0,0 +1 @@
...,[88,230,521,697,729,730,731,895,897,899,901,904,906,908,910,911,915,918],[75,88,232,239,521,697,729,730,731,793,921,922,923],[88,235,239,521,697,729,730,731,893,924,925,926],[88,259,480,492,521,697,729,730,731,928],[88,231,259,521,697,729,730,731],[88,521,697,729,730,731,903],[88,476,494,521,697,729,730,731,931],[88,230,261,521,697,729,730,731],[75,88,235,239,521,697,729,730,731],[88,492,521,697,729,730,731,933],[88,232,235,261,521,697,729,730,731],[75,88,233,235,521,697,729,730,731],[75,88,233,521,697,729,730,731],[75,88,232,521,697,729,730,731],[88,239,521,697,729,730,731,924],[88,230,482,488,492,521,697,729,730,731,918],[88,230,521,697,729,730,731,917],[88,521,697,729,730,731,732],[88,521,697,725,729,730,731],[88,521,697,729,730,731,938],[88,521,592,697,729,730,731,876],[75,88,239,261,521,662,697,729,730,731,873,874,875],[88,235,236,521,697,729,730,731],[88,521,614,697,729,730,731,877,1409],[88,521,697,729,730,731,1410,1556],[88,521,697,729,730,731,1553],[88,521,529,697,729,730,731,1554],[521,523,592,682,697,729,730,731],[88,521,683,697,729,730,731],[88,521,530,697,729,730,731,916],[88,261,521,614,683,697,729,730,731,877,917,1409,1411,1412,1555],[88,288,521,697,729,730,731],[88
```
Comment (ioannakok) [inline dotcom-rendering/tsconfig.tsbuildinfo:1]: Was this committed by accident?

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 2]
```diff
@@ -0,0 +1,438 @@
...
+			supportingContent={trail.supportingContent?.slice(0, 3)}
+			supportingContentAlignment={
+				trail.supportingContent && trail.supportingContent.length > 2
+					? 'horizontal'
+					: 'vertical'
+			}
+			imagePosition="right"
+			imageSize="large"
+			imagePositionOnMobile="top"
+			headlineSize="large"
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:126]:
```suggestion
			headlineSize="large"
			headlineSizeOnMobile="large"
```

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 3]
```diff
@@ -0,0 +1,438 @@
...
+		/>
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:127]:
```suggestion
                 headlineSizeOnMobile="large" 
		/>
```

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 4]
```diff
@@ -0,0 +1,438 @@
...
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:165]:
```suggestion
                headlineSizeOnMobile="large" 
		/>
```

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 5]
```diff
@@ -0,0 +1,438 @@
...
+			containerPalette={containerPalette}
+			showAge={showAge}
+			trailText={trail.trailText}
+			supportingContent={trail.supportingContent?.slice(0, 3)}
+			supportingContentAlignment={
+				trail.supportingContent && trail.supportingContent.length > 2
+					? 'horizontal'
+					: 'vertical'
+			}
+			imagePosition="right"
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:161]:
```suggestion
			imagePosition="left"
```

File: dotcom-rendering/tsconfig.tsbuildinfo (hunk 1 above)
Comment (OllysCoding) [reply dotcom-rendering/tsconfig.tsbuildinfo:1]: Probably yeah not sure why it let me commit it? cc @mxdvl

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 6]
```diff
@@ -0,0 +1,438 @@
...
+	trail,
+	showAge,
+	containerPalette,
+}: TrailProps) => {
+	return (
+		<FrontCard
+			trail={trail}
+			supportingContent={trail.supportingContent?.slice(0, 2)}
+			containerPalette={containerPalette}
+			showAge={showAge}
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:192]: I think I'm missing something here. Why are we not  passing `headlineSize`, `headlineSizeOnMobile`, `imageSize`, `imagePosition`, `imagepositionOnMobile` and `supportingContentAlignment`?

Comment (ioannakok) [reply dotcom-rendering/src/web/lib/cardWrappers.tsx:192]: I have the same question for other wrappers, e.g. `Card25Media25Tall. etc.

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 7]
```diff
@@ -0,0 +1,438 @@
...
+		<FrontCard
+			trail={trail}
+			containerPalette={containerPalette}
+			headlineSize="large"
+			headlineSizeOnMobile="large"
+			imagePositionOnMobile="top"
+			showAge={showAge}
+			supportingContent={trail.supportingContent?.slice(0, 3)}
+			supportingContentAlignment={'horizontal'}
+		/>
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:259]:
```suggestion
               imagePosition="top"
		/>
```

File: dotcom-rendering/src/web/lib/dynamicSlices.tsx [hunk 8]
```diff
@@ -262,37 +231,20 @@ export const Card50_Card25_Card25 = ({
...
-						imagePositionOnMobile="top"
-						supportingContent={trail.supportingContent}
 					/>
 				</LI>
 			))}
 
 			{cards25.map((trail) => (
 				<LI percentage="25%" padSides={true} showDivider={true}>
-					<FrontCard
+					<Card25Media25
```
Comment (ioannakok) [inline dotcom-rendering/src/web/lib/dynamicSlices.tsx:244]: There is some logic about whether to show `trailText` or not being removed in this PR but I cannot see it in [in the wrapper](https://github.com/guardian/dotcom-rendering/blob/b09bf6632ef2bf5e789a03b67750c0f5f3212b84/dotcom-rendering/src/web/lib/cardWrappers.tsx#L182).

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 9]
```diff
@@ -0,0 +1,438 @@
...
+}: TrailProps) => {
+	return (
+		<FrontCard
+			trail={trail}
+			containerPalette={containerPalette}
+			showAge={showAge}
+			headlineSize="huge"
+			headlineSizeOnMobile="large"
+			imageUrl={trail.image}
+			imagePosition={'top'}
```
[the remark this answers is not in the document]
Comment (OllysCoding) [reply dotcom-rendering/src/web/lib/cardWrappers.tsx:85]: I'll do a full review, feel like we should have a linting rule around this

**Review by OllysCoding — COMMENTED** [review]
A few small fixes we had to institute to get everything working correctly:

File: dotcom-rendering/tsconfig.tsbuildinfo (hunk 1 above)
Comment (mxdvl) [reply dotcom-rendering/tsconfig.tsbuildinfo]: Probably because you did not have the `.gitignore`?
Should be removed in #6704  in any case.

File: dotcom-rendering/src/web/components/CardHeadline.tsx [hunk 10]
```diff
@@ -181,8 +181,12 @@ const lineStyles = (palette: Palette) => css`
 		top: 0;
 		left: 0;
 		content: '';
-		width: 120px;
 		border-top: 1px solid ${palette.border.cardSupporting};
+
+		${between.tablet.and.desktop} {
+			width: 100px;
+		}
+		width: 120px;
```
[the remark this answers is not in the document]
Comment (mxdvl) [reply dotcom-rendering/src/web/components/CardHeadline.tsx:189]: I think if you put the `width` after, it will take precendence to the media query… so this does not do anything.

File: dotcom-rendering/src/web/lib/cardWrappers.tsx [hunk 11]
```diff
@@ -0,0 +1,468 @@
...
+		/>
+	);
+};
+
+/**
+ * .__________________.
+ * |##################|
+ * |##################|
+ * |                  |
+ * |__________________|
```
Comment (mxdvl) [inline dotcom-rendering/src/web/lib/cardWrappers.tsx:283]: Just a thought [box drawing](https://en.wikipedia.org/wiki/Box-drawing_character)

```suggestion
 * ┏━━━━━━━━━━━━━━━━━━┱┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┐
 * ┃▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒┃                  ┊
 * ┃▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒┃                  ┊
 * ┃                  ┃                  ┊
 * ┗━━━━━━━━━━━━━━━━━━┹┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┘
```

**Review by mxdvl — APPROVED** [review]
This looks really good, and the ASCII art helps.

At first, I wasn’t sure if a `Card33Media33` would have the image take a third of its size, but the art made it easy to understand.

File: dotcom-rendering/src/web/lib/cardWrappers.tsx (hunk 11 above)
Comment (OllysCoding) [reply dotcom-rendering/src/web/lib/cardWrappers.tsx]: Good idea! Refactor incoming

File: dotcom-rendering/src/web/components/CardHeadline.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (OllysCoding) [reply dotcom-rendering/src/web/components/CardHeadline.tsx:189]: I did verify it works, but I'll move it to be sure :)

**Review by AshCorr — APPROVED** [review]
Looks great!

**Review by ioannakok — APPROVED** [review]

**Review by bryophyta — APPROVED** [review]
looks great, awesome work!
