### PR TITLE
fix: Sort containers for tag fronts

### LINKED ISSUE #8315: Address ordering bug (ensure grouped cards are sorted)
There's an occasional bug where the dated containers display in the wrong order

(Forced example)
image

This should be fixed by sorting the containers created in `groupTrailsByDates.ts` in descending (e.g most recent day first) order.

### PR DESCRIPTION
**Pull request by OllysCoding**
## What does this change?

Closes  #8315.

Sorts the output of `groupedTrails` (containers), to ensure they're always in the intended order.

## Why?

There appeared to be an edge case where it was possible these were created out of order, observed at least once.

### CODE REVIEW

File: dotcom-rendering/src/model/groupTrailsByDates.ts [hunk 1]
```diff
@@ -194,5 +194,19 @@ export const groupTrailsByDates = (
 		}
 	}
 
+	// Sort - in cases where card order is unexpected (e.g not date ordered), it is possible this array will be out of order.
+	groupedTrails.sort((a, b) => {
```
Comment (georgeblahblah) [inline dotcom-rendering/src/model/groupTrailsByDates.ts:198]: my memory of `sort` is always so fuzzy! Could we add a short comment to clarify whether we want to sort most recent items with the latest date first for instance?

**Review by georgeblahblah — APPROVED** [review]

File: dotcom-rendering/src/model/groupTrailsByDates.ts (hunk 1 above)
Comment (OllysCoding) [reply dotcom-rendering/src/model/groupTrailsByDates.ts]: Added :)

[the remark this answers is not in the document]
Comment (OllysCoding) [reply dotcom-rendering/src/model/groupTrailsByDates.ts]: I've added the spreading - it seems that `.toSorted` isn't supported in nodejs & eslint versions used by DCR yet unfortunately, so we'll have to wait a bit longer for that improvement!
