### PR TITLE
fix(zip): remove AR before zipping

### LINKED ISSUE #6767: DCR instance disk space

### PR DESCRIPTION
**Pull request by mxdvl**
Fixes #6767 

## What does this change?

Remove apps-rendering folder before zipping artefact

## Why?

DCR does not need AR’s contents or its node_modules for its PROD artefact.

This reduces the zipped artefact bundle from ~720MB to ~280MB (less than 40% of original size)

## Next steps

- [ ] Audit needed packages for PROD, currently still 1.3GB are shipped in the artefact. We probably only need `pm2` and a handful of other things.
- [ ] Discuss with DevX wether we expect the base image to start at 4.4GB. This seems somewhat high.
- [ ] Make sure we get alerts above certain levels. Report if disk usage at startup is over 80%?
- [ ] Investigate why we are currently using `t4g.small`, min: 9, max: 36. The goal would be to scale vertically instead of horizontally. (Not directly related to this issue but somewhat related and something we should look into at some point.)

### CODE REVIEW

**Review by ioannakok — APPROVED** [review]

**Comment by ioannakok** [comment]
Mobbed on this!

File: dotcom-rendering/scripts/deploy/build-riffraff-bundle.js [hunk 1]
```diff
@@ -1,9 +1,9 @@
 const { promisify } = require('util');
 const writeFile = promisify(require('fs').writeFile);
-
+const cpy = require('cpy');
 const execa = require('execa');
+const rimraf = require('rimraf');
 const path = require('path');
-const cpy = require('cpy');
 const { warn, log } = require('../env/log');
```
Comment (mxdvl) [inline dotcom-rendering/scripts/deploy/build-riffraff-bundle.js:7]: Ordered strangely. Let's keep the diff smaller.
