### PR TITLE
Fix special reports cards text colour

### LINKED ISSUE #4045: Suisse Secrets cards styles
reported by: Rhys Mills (@rhystmills)
via: Dotcom chat channel
on: 22 Feb 2022

> Some inconsistent rendering in the Credit Suisse series:
> https://www.theguardian.com/news/2022/feb/21/switzerland-at-risk-of-eu-blacklist-after-credit-suisse-leak

image

*note the black text on dark grey background*

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Fix Onward card styles in Suisse Secret special report by making `ArticleSpecial.SpecialReport` take precedence over `ArticleDisplay.Immersive`.

## Why?

The text is hard to read and unnaccessible. Fixes #4045 

### Before

image

### After

image

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
🚤

File: dotcom-rendering/src/web/components/CardHeadline.tsx [hunk 1]
```diff
@@ -84,14 +84,20 @@ const labTextStyles = (size: SmallHeadlineSize) => {
...
+
 	function generateUnderlinedCss(baseSize: number) {
 		return css`
 			background-image: linear-gradient(
 				to bottom,
 				transparent,
 				transparent ${baseSize - 1}px,
-				rgba(199, 0, 0, 0.5)
+				${transparentColour}
 			);
```
Comment (mxdvl) [inline dotcom-rendering/src/web/components/CardHeadline.tsx:101]: @oliverlloyd since you’ve review I’ve proposed this. Can split in its own PR if it needs more work.

Comment (mxdvl) [reply dotcom-rendering/src/web/components/CardHeadline.tsx:101]: Added a new branch. Let’s not confuse things.
