### PR TITLE
fix: add altText to fronts cards

### LINKED ISSUE #8144: No alt text on front images

### PR DESCRIPTION
**Pull request by jamesgorrie**
## What does this change?
Fixes #8144 

This changes propagates the data from Composer => Frontend => DCR via the enhancers, and renders the altText on fronts images.

The scope of this PR is to fix fronts to ++➕ our accessibility, which suffers poorly due to this omission, and could also have further reaching negative impact e.g. SEO. There are some questions on potential better solutions 👇 .

There's a comment that alludes to another we might do this, and I think we should, but maybe as a follow up, and a pairing session. 

e.g.
```TS
type Image = { alt: string, src: string; }
```

## Screenshots

| Before      | After      |
| ----------- | ---------- |
| ![before][] | ![after][] |

[before]: https://github.com/guardian/dotcom-rendering/assets/31692/a9249dbc-8158-431a-86f8-a867d7d4e2b4
[after]: https://github.com/guardian/dotcom-rendering/assets/31692/4a2e8e94-b19d-447d-95aa-68711ffba8be

### CODE REVIEW

File: dotcom-rendering/src/types/front.ts [hunk 1]
```diff
@@ -298,6 +298,7 @@ export type DCRFrontCard = {
 	starRating?: number;
 	webPublicationDate?: string;
 	image?: string;
```
Comment (jamesgorrie) [inline dotcom-rendering/src/types/front.ts:300]: My suggestion as per the PR decscription would be to codify that we always expect an altText by making this `{ src: string, alt: string }`.
