### PR TITLE
feat(#5136): Add support for fixed/small/slow-I

### LINKED ISSUE #5136: "fixed/small/slow-I" (`159`) container
Part of https://github.com/guardian/dotcom-rendering/issues/4720

### PR DESCRIPTION
**Pull request by AshCorr**
## What does this change?

Add support for fixed/small/slow-I

Closes #5136 

## Screenshots

| Before      | After      |
|-------------|------------|
| ![before][] | ![after][] |
| ![before2][] | ![after2][] |

[before]: https://user-images.githubusercontent.com/21217225/183670449-1f0d13fe-2c08-4172-b5d8-5f6f03243bf6.png
[after]: https://user-images.githubusercontent.com/21217225/183670547-623f18a1-193c-41e4-a445-8196d40e6183.png

[before2]: https://user-images.githubusercontent.com/21217225/183667960-e8b9e991-890a-4b6f-86f7-021d3641e0a9.png
[after2]: https://user-images.githubusercontent.com/21217225/183667863-c916c2d5-547e-41ad-b7e3-a7b5bd60d33d.png

### CODE REVIEW

File: dotcom-rendering/src/web/components/FixedSmallSlowI.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+export const FixedSmallSlowI = ({
+	trails,
+	containerPalette,
+	showAge,
+}: Props) => {
+	const trail = trails[0];
+
+	return (
+		<FrontCard
```
Comment (AshCorr) [inline dotcom-rendering/src/web/components/FixedSmallSlowI.tsx:18]: Visually it makes no difference wrapping all this in a <UL> and <LI>. I was tempted to keep it all wrapped in a <UL> <LI> for consistency but decided against as we already have some precedent for not using UL LI in Thrashers

**Review by oliverlloyd — APPROVED** [review]
Spot on

**Review by OllysCoding — APPROVED** [review]
Nice one!
